#! /bin/bash

doit=""

if test ! -e ../../wrf.input; then
  echo "You don't seem to be in a WRFV3/run directory... ciao!"
  exit
fi

sed -e 's/\ *=\ */=/' ../../wrf.input > source.it  || exit ${ERROR_MISSING_WRFINPUT}
source source.it && rm source.it
sed -e 's/\ *=\ */=/' ../../wrf.chunk > source.it  || exit ${ERROR_MISSING_WRFCHUNK}
source source.it && rm source.it
export WRF4G_CONF_FILE="../../wrf4g.conf"
export WRF4G_EXPERIMENT="${experiment_name}"
export WRF4G_REALIZATION="${realization_name}"
export PATH="../../WRFGEL:$PATH"

for f in wrfout*; do
  if test "$f" != 'wrfout*'; then
    $doit post_and_register --no-bg out ${f:11} ${f}
  fi
done

for f in wrfrst*; do
  if test $f != 'wrfrst*'; then
    $doit register_file rst ${f:11} ${f}
  fi
done

for f in wrfts*; do
  if test "$f" != 'wrfts*'; then
    $doit register_file ts date_not_used ${f}
  fi
done

for f in wrfxtrm* wrfrain*; do
  if test "$f" = "${f/\*/}"; then
    $doit register_file out ${f:12} ${f}
  fi
done

