#! /bin/bash

doit=""

if test ! -e ../../rootdir; then
  echo "You don't seem to be in a WRFV3/run directory... ciao!"
  exit
else
  ROOTDIR=$(cat ../../rootdir)
fi

TMPFILE=/tmp/source.it

source ${ROOTDIR}/lib/bash/wrf_util.sh
source ${ROOTDIR}/lib/bash/wrf4g_exit_codes.sh

sed -e 's/\ *=\ */=/' ${ROOTDIR}/wrf.input > ${TMPFILE}  || exit ${ERROR_MISSING_WRFINPUT}
source ${TMPFILE} && rm ${TMPFILE}
sed -e 's/\ *=\ */=/' ${ROOTDIR}/wrf.chunk > ${TMPFILE}  || exit ${ERROR_MISSING_WRFCHUNK}
source ${TMPFILE} && rm ${TMPFILE}

export WRF4G_CONF_FILE="${ROOTDIR}/wrf4g.conf"
export WRF4G_EXPERIMENT="${experiment_name}"
export WRF4G_REALIZATION="${realization_name}"
export PATH="${ROOTDIR}/bin:${ROOTDIR}/WRFGEL:${ROOTDIR}/lib/bash:$PATH"
export LD_LIBRARY_PATH="${ROOTDIR}/lib/shared_libs:${LD_LIBRARY_PATH}"

mkdir -p ../../log

for f in wrfout*; do
  if test "$f" != 'wrfout*'; then
    $doit post_and_register --no-bg out ${f:11} ${f}
  fi
done

for f in wrfrst*; do
  if test $f != 'wrfrst*'; then
    $doit register_file rst ${f:11} ${f}
  fi
done

for f in wrfts*; do
  if test "$f" != 'wrfts*'; then
    $doit register_file ts date_not_used ${f}
  fi
done

for f in wrfxtrm* wrfrain*; do
  if test "$f" = "${f/\*/}"; then
    $doit register_file out ${f:12} ${f}
  fi
done

