#! /bin/bash
#
# WRF4G.sh
#
thisdir=$(pwd)
ROOTDIR=/oceano/gmeteo/WORK/chus/wrf4g
#
#  Load functions and set the PATH
#
export PATH="${ROOTDIR}/wn/WRFGEL:$PATH"
#
#  Load wrf4g.conf, wrf.chunk and wrf.input
#
source wrf4g.conf
sed -e 's/\ *=\ */=/' wrf.chunk > source.it
source source.it && rm source.it
sed -e 's/\ *=\ */=/' wrf.input > source.it
source source.it && rm source.it
#
#  Export variables
#
export WRF4G_CONF_FILE="${thisdir}/wrf4g.conf"
export WRF4G_EXPERIMENT="${experiment_name}"
export WRF4G_REALIZATION="${realization_name}"
