#! /usr/bin/python
from vcp import *  
from commands import getstatusoutput
from optparse import OptionParser


usage="""%prog 

Example: %prog 

This command needs that the following environment variables have been established: WRF4G_EXPERIMENT, 
WRF4G_REALIZATION and WRF4G_CONF_FILE.
"""
# Check the Arguments
parser = OptionParser(usage,version="%prog 1.0")
parser.add_option("-v", "--verbose",action="store_true", dest="verbose", default=False,help="Verbose mode. Explain what is being done")
(options, args) = parser.parse_args()

verbose=options.verbose

if verbose: stderr.write("create_output_structure in debug mode ....\n")

if len(args) != 0 :
  parser.error("Incorrect number of arguments. This script doesn't take any arguments.")
  exit(1)
# Check that the environment variables has been established and import their values
env_var={"WRF4G_EXPERIMENT": "" , "WRF4G_REALIZATION": "","WRF4G_CONF_FILE": ""}
env_var=get_env_vars(env_var)
exec(open(env_var["WRF4G_CONF_FILE"]).read())
# List all the variables in the script and search WRF4G_BASEPATH
if WRF4G_BASEPATH in dir():
  stderr.write("Error: WRF4G_BASEPATH is not defined \n")
  exit(1)
  
# Load the URL into the VCPURL class
for dir in ["output","restart","wpsout"]:
  repo="%s/experiments/%s/%s/%s" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"],dir)
  list=VCPURL(repo)
  list.mkdir(verbose=verbose)
