#!/usr/bin/env python

from commands import getstatusoutput
from optparse import OptionParser
import os
import sys  
try:
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..','lib','python'))
    import vcplib
except Exception, e:
    print 'Caught exception: %s: %s' % (e.__class__, str(e))
    traceback.print_exc(file=sys.stdout)
    sys.exit(-1)


usage="""%prog type date

Example:    %prog rst 1990-01-01_00:00:00 
            %prog real 1990-01-01_00:00:00

This command needs that the following environment variables have been established: WRF4G_EXPERIMENT, WRF4G_REALIZATION and RESOURCES_WRF4G.
"""

# Check the Arguments
parser = OptionParser(usage,version="%prog 1.0")
parser.add_option("-v", "--verbose",action="store_true", dest="verbose", default=False,help="Verbose mode. Explain what is being done")
(options, args) = parser.parse_args()

verbose=options.verbose

if len(args) == 2 :
    type, date  = args
else :
    parser.error("Incorrect number of arguments")
    sys.exit(-1)

# Check that the environment variables has been established and import their values
env_var = {}
for var in [ "WRF4G_EXPERIMENT" , "WRF4G_REALIZATION", "RESOURCES_WRF4G"] :
    var_value = os.getenv(var)
    if not var_value :
        sys.stderr.write( var + " is not defined\n")
        sys.exit(-1)
    env_var[var] = var_value

exec(open(env_var["RESOURCES_WRF4G"]).read())
# List all the variables in the script and search WRF4G_BASEPATH
if not 'WRF4G_BASEPATH' in dir():
    sys.stderr.write("Error: WRF4G_BASEPATH is not defined\n")
    sys.exit(-1)

sys.stderr.write("WRFGEL(download_file)> START: %s\n" % args)

type_list={
           "rst"  : "restart",
           "real" : "realout"
           }

pattern = {
           "rst"  : "wrfrst*"           + date + "*" ,
           "real" : "wrf[lbif]*_d\d\d_" + date + "*"
           } 

orig_folder="%s/%s/%s/%s" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"],type_list[type])
orig_c=vcplib.VCPURL(orig_folder)

for file in orig_c.ls(pattern[type]):
    # file will follow the pattern: wrfrst_d01_19900101T000000Z.nc or wrflowinp_d08_19900101T000000Z.nc
    file_c=vcplib.wrffile(file)
    if type == "rst" :
        dest=file_c.file_name + file_c.date_wrf()
    else: 
        # From wrflowinp_d08_ we remove the _ at the end
        dest=file_c.file_name[:-1]
    if verbose: 
        sys.stderr.write("origin: %s destiny: %s \n" % (orig_folder + "/" + file ,dest))
    try:
        vcplib.copy_file( orig_folder + "/" + file ,dest, verbose=verbose)
    except Exception, e:
        sys.stderr(file + " has not copied to " + dest + "\n")
        sys.exit(-1)
    sys.stderr.write("WRFGEL(download_file)> END: %s\n" % args)
