#!/usr/bin/python

from vcp import *      
from commands import getstatusoutput
from optparse import OptionParser
from sys import exit   
from os.path import basename 
from re import search
from os import getenv

WRF4G_CONF_FILE_NOT_DEFINED=1
DATE_BAD_FORMED=2
TOO_MANY_DATES=3

usage="""%  prog date 
        % prog 19910101T120000Z
        
This command needs that the following environment variables have been established: WRF4G_EXPERIMENT, 
WRF4G_REALIZATION and WRF4G_CONF_FILE.
"""
# Check the Arguments
parser = OptionParser(usage,version="%prog 1.0")
parser.add_option("-v", "--verbose",action="store_true", dest="verbose", default=False,help="Verbose mode. Explain what is being done")
(options, args) = parser.parse_args()

if len(args) != 1 :
  parser.error("Incorrect number of arguments. This script doesn't take any arguments.")
  exit(1)
  
date=args[0]

# Check that the environment variables has been established and import their values
env_var={"WRF4G_EXPERIMENT": "" , "WRF4G_REALIZATION": "","WRF4G_CONF_FILE": ""}
env_var=get_env_vars(env_var)
exec(open(env_var["WRF4G_CONF_FILE"]).read())
# List all the variables in the script and search WRF4G_BASEPATH
if not 'WRF4G_BASEPATH' in dir():
  print "Error: WRF4G_BASEPATH is not defined"
  exit(1)

# Load the URL into the VCPURL class
repo="%s/experiments/%s/%s/wpsout" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"])
if options.verbose: print repo
list=VCPURL(repo)

# List all the wps files for this date
restart_list=list.ls("wrf[lbi]*_d\d\d_" + date + "*")

import os.path
domains = map(lambda x: x.split('_')[1], map(os.path.basename, restart_list))
d = {}
for x in domains:
  d[x]=x
domains = d.values()
domains.sort()

rval = 1

for dom in domains:
  if dom == 'd01' and not "wrfbdy_%s_%s.nc" % (dom, date) in restart_list:
      rval = 0
  if not "wrfinput_%s_%s.nc" % (dom, date) in restart_list:
    rval = 0
#  if not "wrflowinp_%s_%s.nc" % (dom, date) in restart_list:
#    rval = 0

print rval
