#!/usr/bin/env python
      
from commands import getstatusoutput
from optparse import OptionParser
import sys   
import os  

try:
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..','lib','python'))
    import vcplib
except Exception, e:
    print 'Caught exception: %s: %s' % (e.__class__, str(e))
    traceback.print_exc(file=sys.stdout)
    sys.exit(-1)

usage="""%prog file_type date [file_name] [file_end_date]

Example: %prog rst 1990-01-01_00:00:00 wrfrst_d01_1990-01-01_00:00:00
         %prog out 1990-01-01_00:00:00 wrfout_d01_1990-01-01_00:00:00 1991-03-01_00:00:00
         %prog wps 1990-01-01_00:00:00

This command needs that the following environment variables have been established: WRF4G_EXPERIMENT, WRF4G_REALIZATION and RESOURCES_WRF4G.
"""
# Check the Arguments
parser = OptionParser(usage,version="%prog 1.0")
parser.add_option("-v", "--verbose",action="store_true", dest="verbose", default=False,help="Verbose mode. Explain what is being done")
(options, args) = parser.parse_args()
verbose=options.verbose

type_list = {
             "rst" : "restart",
             "out" : "output",
             }

file_end_date=None
sys.stderr.write("WRFGEL(register_file)> START: %s\n" % args)

if len(args) == 4 and args[0] == "out":
    [type,date,file,file_end_date] = args
elif len(args) == 3 and args[0] in type_list.keys() + ["ts",]:
    [type,date,file] = args
elif len(args) == 2 and args[0] == "wps":
    [type,date] = args
else:
    parser.error("Incorrect number of arguments")
    sys.exit(1)

# Check that the environment variables has been established and import their values
env_var = {}
for var in [ "WRF4G_EXPERIMENT" , "WRF4G_REALIZATION", "RESOURCES_WRF4G"] :
    var_value = os.getenv(var)
    if not var_value :
        sys.stderr.write( var + " is not defined\n")
        sys.exit(-1)
    env_var[var] = var_value
exec(open(env_var["RESOURCES_WRF4G"]).read())
# List all the variables in the script and search WRF4G_BASEPATH
if not 'WRF4G_BASEPATH' in dir():
    sys.stderr.write("Error: WRF4G_BASEPATH is not defined\n")
    sys.exit(-1)

# Change the name of the file in the repository (Change date to the iso format
# and add .nc at the end of the name
if type in type_list.keys() :
    if type == "out" and file_end_date:
        file_o=vcplib.wrffile(file,file_end_date)
        dest_file=file_o.file_name_out_iso()
    else:
        file_o=vcplib.wrffile(file)
        dest_file=file_o.file_name_iso()
        
    dest_folder="%s/%s/%s/%s" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"],type_list[type])
    dest= dest_folder + "/" + dest_file
    
    if verbose:
        sys.stderr.write( "Copying %s -> %s\n" %(file, dest))
    try:
        vcplib.copy_file(file,dest +".part", verbose=verbose)
    except Exception, e:
        sys.stderr(file + " has not copied to " + dest + "\n")
        sys.exit(-1)
    vcplib.VCPURL(dest + ".part").rename(os.path.basename(dest))
    input=vcplib.VCPURL(file)
    # Delete the file from local disk
    if verbose:
        sys.stderr.write("Deleting file %s\n" %file)
    input.rm()

elif type == "ts":
    dest_folder="%s/%s/%s/output" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"])
    dest= dest_folder + "/" + file
    if verbose:
        sys.stderr.write( "Copying %s -> %s\n" %(file, dest))
    try:
        vcplib.copy_file(file,dest +".part", verbose=verbose)
    except Exception, e:
        sys.stderr(file + " has not copied to " + dest + "\n")
        sys.exit(-1)
    vcplib.VCPURL(dest + ".part").rename(os.path.basename(dest))
    input=vcplib.VCPURL(file)
    # Delete the file from local disk
    if verbose:
        sys.stderr.write("Deleting file %s\n" %file)
    input.rm()

else :
    # If the files are WPS, add the date to the name. Three files have to be uploaded: wrfinput_d0?,wrfbdy_d0? and wrflowinp_d0?
    #The command: $ upload_file wps     1990-01-01_00:00:00
    # will create in the repositore three files with the following format: wrfinput_d01_19900101T000000Z
    wps_dir=vcplib.VCPURL(".")
    wps_files=wps_dir.ls("wrf[lbif]*_d\d\d")
    suffix="_" + vcplib.datetime2dateiso(vcplib.datewrf2datetime(date))+ ".nc"
    
    for wps_file in wps_files :
        dest_file=os.path.basename(wps_file)
        dest="%s/%s/%s/%s/%s%s" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"],"realout",dest_file,suffix)
        if verbose:
            sys.stderr.write("origin: %s destiny: %s\n" % (wps_file,dest))
        try:
            vcplib.copy_file(wps_file,dest, verbose=verbose)
        except Exception, e:
            sys.stderr(wps_file + " has not copied to " + dest + "\n")
            sys.exit(-1)
    
sys.stderr.write("WRFGEL(register_file)> END: %s\n" % args)
