#!/usr/bin/python
from vcp import *      
from commands import getstatusoutput
from optparse import OptionParser
from sys import exit   
from os.path import basename

WRF4G_CONF_FILE_NOT_DEFINED=1
DATE_BAD_FORMED=2
TOO_MANY_DATES=3

usage="""%prog file_type date [file_name]

Example: %prog rst 1990-01-01_00:00:00 wrfrst_d01_1990-01-01_00:00:00
         %prog out 1990-01-01_00:00:00 wpsout_d01_1990-01-01_00:00:00
         %prog wps 1990-01-01_00:00:00

This command needs that the following environment variables have been established: WRF4G_EXPERIMENT, WRF4G_REALIZATION and WRF4G_CONF_FILE.
"""
# Check the Arguments
parser = OptionParser(usage,version="%prog 1.0")
parser.add_option("-v", "--verbose",action="store_true", dest="verbose", default=False,help="Verbose mode. Explain what is being done")
(options, args) = parser.parse_args()

type_list={"rst":"restart","out":"output" }
if len(args) == 3 and args[0] in type_list.keys():
  [type,date,file] = args
  
elif len(args) ==2 and args[0] == "wps" :
  [type,date] = args

else :
  parser.error("Incorrect number of arguments")
  exit(1)

# Check that the environment variables has been established and import their values
env_var={"WRF4G_EXPERIMENT": "" , "WRF4G_REALIZATION": "","WRF4G_CONF_FILE": ""}
env_var=get_env_vars(env_var)
exec(open(env_var["WRF4G_CONF_FILE"]).read())
# List all the variables in the script and search WRF4G_BASEPATH
if WRF4G_BASEPATH in dir():
  print "Error: WRF4G_BASEPATH is not defined"
  exit(1)

# Change the name of the file in the repository (Change date to the iso format
# and add .nc at the end of the name
if type in type_list.keys() :
    file_o=wrffile(file)
    dest_file=file_o.file_name_iso()
 
    dest="%s/experiments/%s/%s/%s/%s" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"],type_list[type],dest_file)
    if options.verbose: print "origin: %s destiny: %s" % (file,dest) 
    output=copy_file(file,dest)
    print output

else :    
    # If the files are WPS, add the date to the name. Three files have to be uploaded: wrfinput_d0?,wrfbdy_d0? and wrflowinp_d0?
    #The command: $ upload_file wps     1990-01-01_00:00:00
    # will create in the repositore three files with the following format: wrfinput_d01_19900101T000000
    wps_dir=VCPURL(".")
    wps_files=wps_dir.ls("wrf[lbi]*_d\d\d")    
    suffix="_" + datetime2dateiso(datewrf2datetime(date))+ ".nc"

    for wps_file in wps_files :
        dest_file=basename(wps_file)
        dest="%s/experiments/%s/%s/%s/%s%s" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"],"wpsout",dest_file,suffix)
        if options.verbose: print "origin: %s destiny: %s" % (wps_file,dest) 
        output=copy_file(wps_file,dest, verbose=options.verbose) 
        print output
