#!/usr/bin/python
from vcp import *      
from commands import getstatusoutput
from optparse import OptionParser
from sys import exit   
from sys import stderr  
from os.path import basename
import WRF4G


WRF4G_CONF_FILE_NOT_DEFINED=1
DATE_BAD_FORMED=2
TOO_MANY_DATES=3

usage="""%prog file_type date [file_name]

Example: %prog rst 1990-01-01_00:00:00 wrfrst_d01_1990-01-01_00:00:00
         %prog out 1990-01-01_00:00:00 wrfout_d01_1990-01-01_00:00:00
         %prog wps 1990-01-01_00:00:00

This command needs that the following environment variables have been established: WRF4G_EXPERIMENT, WRF4G_REALIZATION and WRF4G_CONF_FILE.
"""
# Check the Arguments
parser = OptionParser(usage,version="%prog 1.0")
parser.add_option("-v", "--verbose",action="store_true", dest="verbose", default=False,help="Verbose mode. Explain what is being done")
(options, args) = parser.parse_args()
verbose=options.verbose


type_list = {
  "rst" : "restart",
  "out" : "output",
}

stderr.write("WRFGEL(register_file)> START: %s\n" % args)

if len(args) == 3 and args[0] in type_list.keys() + ["ts",]:
  [type,date,file] = args
elif len(args) == 2 and args[0] == "wps":
  [type,date] = args
else:
  parser.error("Incorrect number of arguments")
  exit(1)

# Check that the environment variables has been established and import their values
env_var={"WRF4G_EXPERIMENT": "" , "WRF4G_REALIZATION": "","WRF4G_CONF_FILE": ""}
env_var=get_env_vars(env_var)
exec(open(env_var["WRF4G_CONF_FILE"]).read())
# List all the variables in the script and search WRF4G_BASEPATH
if not 'WRF4G_BASEPATH' in dir():
  stderr.write("Error: WRF4G_BASEPATH is not defined\n")
  exit(1)

# Change the name of the file in the repository (Change date to the iso format
# and add .nc at the end of the name
if type in type_list.keys() :
    file_o=wrffile(file)
    dest_file=file_o.file_name_iso()
    
    dest_folder="%s/experiments/%s/%s/%s" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"],type_list[type])
    dest= dest_folder + "/" + dest_file
    
    if verbose: stderr.write( "Copying %s -> %s\n" %(file, dest))
    output=copy_file(file,dest +".part", verbose=verbose)
    if verbose: stderr.write(output + "\n")
    VCPURL(dest + ".part").rename(basename(dest))
    if type == "rst":
    	data={'name': env_var["WRF4G_REALIZATION"]}
        r=WRF4G.Realization(data)
        r.set_restart(date)   

    input=VCPURL(file)
    # Delete the file from local disk 
    if verbose: stderr.write("Deleting file %s\n" %file)
    input.rm()

elif type == "ts":
    dest_folder="%s/experiments/%s/%s/output" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"])
    dest= dest_folder + "/" + file
    if verbose: stderr.write( "Copying %s -> %s\n" %(file, dest))
    output=copy_file(file,dest +".part", verbose=verbose)
    if verbose: stderr.write(output + "\n")
    VCPURL(dest + ".part").rename(basename(dest))
    input=VCPURL(file)
    # Delete the file from local disk 
    if verbose: stderr.write("Deleting file %s\n" %file)
    input.rm()

else :    
    # If the files are WPS, add the date to the name. Three files have to be uploaded: wrfinput_d0?,wrfbdy_d0? and wrflowinp_d0?
    #The command: $ upload_file wps     1990-01-01_00:00:00
    # will create in the repositore three files with the following format: wrfinput_d01_19900101T000000Z
    wps_dir=VCPURL(".")
    wps_files=wps_dir.ls("wrf[lbif]*_d\d\d")   

    suffix="_" + datetime2dateiso(datewrf2datetime(date))+ ".nc"

    for wps_file in wps_files :
        dest_file=basename(wps_file)
        dest="%s/experiments/%s/%s/%s/%s%s" % (WRF4G_BASEPATH,env_var["WRF4G_EXPERIMENT"],env_var["WRF4G_REALIZATION"],"wpsout",dest_file,suffix)
        if verbose:
             stderr.write("origin: %s destiny: %s\n" % (wps_file,dest))
        output=copy_file(wps_file,dest, verbose=verbose) 
        if verbose: stderr.write(output + "\n")

stderr.write("WRFGEL(register_file)> END: %s\n" % args)
